# See https://taskfile.dev/
#
# e.g. `task -w test`
version: "3"

tasks:
  build:
    cmds:
      - go build -o ../build/udm-client
    sources:
      - "**/*.go"

  test:
    cmds:
      - go test ./...
    sources:
      - "**/*.go"

  test-cov:
    cmds:
      - go test -cover ./...
    sources:
      - "**/*.go"

  test-cov-html:
    cmds:
      - go test -coverprofile=../build/coverage.out ./...
      - go tool cover -html=../build/coverage.out -o ../build/coverage.html
    sources:
      - "**/*.go"
